//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.yServiceSoap")]
    public interface yServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 logistics_No 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfo", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.GetInfoResponse GetInfo(WindowsFormsApplication1.ServiceReference1.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.GetInfoResponse> GetInfoAsync(WindowsFormsApplication1.ServiceReference1.GetInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 logistics_No 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetExam", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.SetExamResponse SetExam(WindowsFormsApplication1.ServiceReference1.SetExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetExam", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SetExamResponse> SetExamAsync(WindowsFormsApplication1.ServiceReference1.SetExamRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfo", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.GetInfoRequestBody Body;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(WindowsFormsApplication1.ServiceReference1.GetInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string logistics_No;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string app_No;
        
        public GetInfoRequestBody() {
        }
        
        public GetInfoRequestBody(string logistics_No, string app_No) {
            this.logistics_No = logistics_No;
            this.app_No = app_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.GetInfoResponseBody Body;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(WindowsFormsApplication1.ServiceReference1.GetInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoResult;
        
        public GetInfoResponseBody() {
        }
        
        public GetInfoResponseBody(string GetInfoResult) {
            this.GetInfoResult = GetInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetExam", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SetExamRequestBody Body;
        
        public SetExamRequest() {
        }
        
        public SetExamRequest(WindowsFormsApplication1.ServiceReference1.SetExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string logistics_No;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string app_No;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int checkWay;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int checkResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int inspectionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string result;
        
        public SetExamRequestBody() {
        }
        
        public SetExamRequestBody(string logistics_No, string app_No, int checkWay, int checkResult, int inspectionStatus, string result) {
            this.logistics_No = logistics_No;
            this.app_No = app_No;
            this.checkWay = checkWay;
            this.checkResult = checkResult;
            this.inspectionStatus = inspectionStatus;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetExamResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SetExamResponseBody Body;
        
        public SetExamResponse() {
        }
        
        public SetExamResponse(WindowsFormsApplication1.ServiceReference1.SetExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetExamResult;
        
        public SetExamResponseBody() {
        }
        
        public SetExamResponseBody(string SetExamResult) {
            this.SetExamResult = SetExamResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface yServiceSoapChannel : WindowsFormsApplication1.ServiceReference1.yServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class yServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.yServiceSoap>, WindowsFormsApplication1.ServiceReference1.yServiceSoap {
        
        public yServiceSoapClient() {
        }
        
        public yServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public yServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public yServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public yServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.GetInfoResponse WindowsFormsApplication1.ServiceReference1.yServiceSoap.GetInfo(WindowsFormsApplication1.ServiceReference1.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public string GetInfo(string logistics_No, string app_No) {
            WindowsFormsApplication1.ServiceReference1.GetInfoRequest inValue = new WindowsFormsApplication1.ServiceReference1.GetInfoRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.GetInfoRequestBody();
            inValue.Body.logistics_No = logistics_No;
            inValue.Body.app_No = app_No;
            WindowsFormsApplication1.ServiceReference1.GetInfoResponse retVal = ((WindowsFormsApplication1.ServiceReference1.yServiceSoap)(this)).GetInfo(inValue);
            return retVal.Body.GetInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.GetInfoResponse> WindowsFormsApplication1.ServiceReference1.yServiceSoap.GetInfoAsync(WindowsFormsApplication1.ServiceReference1.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.GetInfoResponse> GetInfoAsync(string logistics_No, string app_No) {
            WindowsFormsApplication1.ServiceReference1.GetInfoRequest inValue = new WindowsFormsApplication1.ServiceReference1.GetInfoRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.GetInfoRequestBody();
            inValue.Body.logistics_No = logistics_No;
            inValue.Body.app_No = app_No;
            return ((WindowsFormsApplication1.ServiceReference1.yServiceSoap)(this)).GetInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.SetExamResponse WindowsFormsApplication1.ServiceReference1.yServiceSoap.SetExam(WindowsFormsApplication1.ServiceReference1.SetExamRequest request) {
            return base.Channel.SetExam(request);
        }
        
        public string SetExam(string logistics_No, string app_No, int checkWay, int checkResult, int inspectionStatus, string result) {
            WindowsFormsApplication1.ServiceReference1.SetExamRequest inValue = new WindowsFormsApplication1.ServiceReference1.SetExamRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SetExamRequestBody();
            inValue.Body.logistics_No = logistics_No;
            inValue.Body.app_No = app_No;
            inValue.Body.checkWay = checkWay;
            inValue.Body.checkResult = checkResult;
            inValue.Body.inspectionStatus = inspectionStatus;
            inValue.Body.result = result;
            WindowsFormsApplication1.ServiceReference1.SetExamResponse retVal = ((WindowsFormsApplication1.ServiceReference1.yServiceSoap)(this)).SetExam(inValue);
            return retVal.Body.SetExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SetExamResponse> WindowsFormsApplication1.ServiceReference1.yServiceSoap.SetExamAsync(WindowsFormsApplication1.ServiceReference1.SetExamRequest request) {
            return base.Channel.SetExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SetExamResponse> SetExamAsync(string logistics_No, string app_No, int checkWay, int checkResult, int inspectionStatus, string result) {
            WindowsFormsApplication1.ServiceReference1.SetExamRequest inValue = new WindowsFormsApplication1.ServiceReference1.SetExamRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SetExamRequestBody();
            inValue.Body.logistics_No = logistics_No;
            inValue.Body.app_No = app_No;
            inValue.Body.checkWay = checkWay;
            inValue.Body.checkResult = checkResult;
            inValue.Body.inspectionStatus = inspectionStatus;
            inValue.Body.result = result;
            return ((WindowsFormsApplication1.ServiceReference1.yServiceSoap)(this)).SetExamAsync(inValue);
        }
    }
}
